"""Add QR validation event

Revision ID: e7d8e4869471
Revises: 58ed056bce80
Create Date: 2026-05-13 10:07:58.915893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8e4869471'
down_revision: Union[str, Sequence[str], None] = '58ed056bce80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_validation_events',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('scanner_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['scanner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_validation_events_business_id'), 'qr_validation_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_qr_validation_events_card_id'), 'qr_validation_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_qr_validation_events_id'), 'qr_validation_events', ['id'], unique=False)
    op.create_index(op.f('ix_qr_validation_events_jti'), 'qr_validation_events', ['jti'], unique=True)
    op.create_index(op.f('ix_qr_validation_events_scanner_id'), 'qr_validation_events', ['scanner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_validation_events_scanner_id'), table_name='qr_validation_events')
    op.drop_index(op.f('ix_qr_validation_events_jti'), table_name='qr_validation_events')
    op.drop_index(op.f('ix_qr_validation_events_id'), table_name='qr_validation_events')
    op.drop_index(op.f('ix_qr_validation_events_card_id'), table_name='qr_validation_events')
    op.drop_index(op.f('ix_qr_validation_events_business_id'), table_name='qr_validation_events')
    op.drop_table('qr_validation_events')
    # ### end Alembic commands ###
